apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-adnr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/bootstrap/integration-e2e-tenant/integ-app-khag/hacbs-test-project-adnr@sha256:3dbd955682a254e022081b4339342baf5d8a122fc269bdf75ba1520a51045132
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
