apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-adnr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-adnr
    app.kubernetes.io/part-of: integ-app-khag
  name: hacbs-test-project-adnr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-adnr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-adnr
    spec:
      containers:
      - image: quay.io/bootstrap/integration-e2e-tenant/integ-app-khag/hacbs-test-project-adnr@sha256:3dbd955682a254e022081b4339342baf5d8a122fc269bdf75ba1520a51045132
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
